export const pAmagProTime_defaultUseTicketNomberInText = true
export const pAmagProTime_defaultHighLatencyMode = true
export const pAmagProTime_defaultForceHighLatencyMode = false
export const pAmagProTime_defaultUseProTimeTestMode = false
export const pAmagProTime_defaultUseMatchBookingDay = true
export const pAmagProTime_defaultUseAutoSelectDay = false
export const dateNow = new Date();
export const dateMonth = dateNow.getMonth();
export const moduleStorage_preValueConfiguration = 'tc_c_module'
export const moduleStorage_preValueSystem = 'tc_s_module'